### ISSUE TITLE
How to use MockTracer and HTTP_HEADERS

### ISSUE THREAD

**Issue by kasium** [opentracing/opentracing-python#145]
Hello,

I would like to use MockTracer and HTTP_HEADERS, but all I get is a SpanContextCorruptedException

```python
import opentracing
import opentracing.mocktracer

opentracing.tracer = opentracing.mocktracer.MockTracer()
opentracing.tracer.extract(opentracing.propagation.Format.HTTP_HEADERS, {"host": "localhost"})
```

```
Traceback (most recent call last):
  File "dumm.py", line 5, in <module>
    opentracing.tracer.extract(opentracing.propagation.Format.HTTP_HEADERS, {"host": "localhost"})
  File "venv/lib/python3.7/site-packages/opentracing/mocktracer/tracer.py", line 185, in extract
    return self._propagators[format].extract(carrier)
  File "venv/lib/python3.7/site-packages/opentracing/mocktracer/text_propagator.py", line 62, in extract
    raise SpanContextCorruptedException()
opentracing.propagation.SpanContextCorruptedException
```

It seems like the default propagator for HTTP_HEADERS is not suitable for HTTP_HEADERS but only for TEXT_MAP.
Can you please support?

**Comment by kasium** [comment]
I'm sorry, there was an inject missing
